server:
  port: 8080
spring:
  application.name: web
  profiles:
    active: test
  jackson:
    #    接口返回的数据的日期格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #    客户端传递的日期格式
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd HH:mm:ss
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
# 日志级别配置
logging:
  level:
    root: info
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: status
      logic-delete-value: 0
      logic-not-delete-value: 1
  mapper-locations: classpath:/mapping/*.xml
  typeAliasesPackage: com.example.model.entity

# 配置接口文档展示，需要自定义 SwaggerConfig 类
springdoc:
  info:
    title: web项目接口文档
    version: v1.0.0
    desc: web项目接口文档描述
